networks:
  backend:
    driver: bridge

services:
  db:
    image: postgres:17.4-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  meili:
    image: getmeili/meilisearch:v1.14.0
    container_name: meilisearch
    restart: always
    environment:
      MEILI_MASTER_KEY: devkey
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:7700/health']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '7700:7700'
    networks:
      - backend

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9090"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - minio_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  minio_data:
